"""add program column to users

Revision ID: 858852e5e20c
Revises: 
Create Date: 2026-04-27 17:02:24.744470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '858852e5e20c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_voter_participation_id', table_name='voter_participation')
    op.drop_table('voter_participation')
    op.drop_index('ix_positions_id', table_name='positions')
    op.drop_table('positions')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_encrypted_votes_id', table_name='encrypted_votes')
    op.drop_table('encrypted_votes')
    op.drop_index('ix_elections_id', table_name='elections')
    op.drop_table('elections')
    op.drop_index('ix_candidates_id', table_name='candidates')
    op.drop_table('candidates')
    op.drop_index('ix_he_tallies_id', table_name='he_tallies')
    op.drop_table('he_tallies')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_index('ix_audit_logs_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_timestamp', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_notifications_id', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('election_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('notification_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], name='notifications_election_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notifications_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    op.create_index('ix_notifications_id', 'notifications', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('election_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], name='audit_logs_election_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='audit_logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='audit_logs_pkey')
    )
    op.create_index('ix_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index('ix_audit_logs_id', 'audit_logs', ['id'], unique=False)
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_table('he_tallies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('election_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('position_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('candidate_order_json', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('encrypted_tally_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('decrypted_tally_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('decrypted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], name='he_tallies_election_id_fkey'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name='he_tallies_position_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='he_tallies_pkey'),
    sa.UniqueConstraint('election_id', 'position_id', name='uq_tally_position')
    )
    op.create_index('ix_he_tallies_id', 'he_tallies', ['id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('position_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('manifesto', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('party_affiliation', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('photo_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('approval_status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='approvalstatus'), autoincrement=False, nullable=False),
    sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('profile_views', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('applied_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name='candidates_position_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='candidates_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='candidates_pkey'),
    sa.UniqueConstraint('user_id', 'position_id', name='uq_candidate_position')
    )
    op.create_index('ix_candidates_id', 'candidates', ['id'], unique=False)
    op.create_table('elections',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('elections_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nomination_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('nomination_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('voting_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('voting_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'NOMINATION_OPEN', 'VOTING_OPEN', 'CLOSED', 'RESULTS_PUBLISHED', name='electionstatus'), autoincrement=False, nullable=False),
    sa.Column('candidates_locked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('results_published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('he_public_key_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('he_private_key_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('he_key_fingerprint', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('he_tally_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='elections_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='elections_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_elections_id', 'elections', ['id'], unique=False)
    op.create_table('encrypted_votes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('election_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('position_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('participation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('encrypted_ballot_json', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], name='encrypted_votes_election_id_fkey'),
    sa.ForeignKeyConstraint(['participation_id'], ['voter_participation.id'], name='encrypted_votes_participation_id_fkey'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name='encrypted_votes_position_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='encrypted_votes_pkey')
    )
    op.create_index('ix_encrypted_votes_id', 'encrypted_votes', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tu_registration_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('faculty', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('STUDENT', 'CANDIDATE', 'ELECTION_HEAD', name='userrole'), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id_card_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('tu_registration_number', name='users_tu_registration_number_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('positions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('election_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('max_votes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], name='positions_election_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='positions_pkey')
    )
    op.create_index('ix_positions_id', 'positions', ['id'], unique=False)
    op.create_table('voter_participation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('voter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('election_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('voted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('confirmation_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], name='voter_participation_election_id_fkey'),
    sa.ForeignKeyConstraint(['voter_id'], ['users.id'], name='voter_participation_voter_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='voter_participation_pkey'),
    sa.UniqueConstraint('voter_id', 'election_id', name='uq_voter_election')
    )
    op.create_index('ix_voter_participation_id', 'voter_participation', ['id'], unique=False)
    # ### end Alembic commands ###
