"""removed phone from students table

Revision ID: f34470997f02
Revises: ce345340f800
Create Date: 2026-03-13 15:51:35.346485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f34470997f02'
down_revision: Union[str, Sequence[str], None] = 'ce345340f800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('phone', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
